apiVersion: v1
kind: Service
metadata:
  name: orderingdb
  namespace: dev
  labels:
    app.kubernetes.io/name: orderingdb
    app.kubernetes.io/part-of: test-microservice
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: orderingdb
  ports:
    - port: 5432
      targetPort: postgres
      name: postgres
