apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbus
  namespace: prod
  labels:
    app.kubernetes.io/name: eventbus
    app.kubernetes.io/part-of: test-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: eventbus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eventbus
        app.kubernetes.io/part-of: test-microservice
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: eshop
            - name: RABBITMQ_DEFAULT_PASS
              value: eshop
            - name: RABBITMQ_DEFAULT_VHOST
              value: /
          readinessProbe:
            tcpSocket:
              port: amqp
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: amqp
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi

