apiVersion: v1
kind: Service
metadata:
  name: eventbus
  namespace: prod
  labels:
    app.kubernetes.io/name: eventbus
    app.kubernetes.io/part-of: test-microservice
spec:
  selector:
    app.kubernetes.io/name: eventbus
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp
    - name: management
      port: 15672
      targetPort: management
  type: ClusterIP

