apiVersion: v1
kind: Service
metadata:
  name: catalogdb
  namespace: prod
  labels:
    app.kubernetes.io/name: catalogdb
    app.kubernetes.io/part-of: test-microservice
spec:
  selector:
    app.kubernetes.io/name: catalogdb
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  type: ClusterIP

