apiVersion: v1
kind: Service
metadata:
  name: identity-api
  namespace: dev
  labels:
    app.kubernetes.io/name: identity-api
    app.kubernetes.io/part-of: test-microservice
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: testmicroservice-dev-identity
spec:
  selector:
    app.kubernetes.io/name: identity-api
  ports:
    - name: http
      port: 80
      targetPort: http
  type: LoadBalancer
