apiVersion: v1
kind: ConfigMap
metadata:
  name: basket-api-config
  namespace: dev
data:
  ASPNETCORE_URLS: http://+:8080
  ASPNETCORE_ENVIRONMENT: Development
  ConnectionStrings__Redis: redis:6379
  ConnectionStrings__EventBus: amqp://eshop:eshop@eventbus:5672/
  Identity__Url: https://YOUR_IDENTITY_HOST
