apiVersion: v1
kind: Service
metadata:
  name: monitoring-blackbox-exporter
  namespace: prod
  labels:
    app.kubernetes.io/name: monitoring-blackbox-exporter
    app.kubernetes.io/part-of: test-microservice
spec:
  selector:
    app.kubernetes.io/name: monitoring-blackbox-exporter
  ports:
    - name: http
      port: 9115
      targetPort: http
  type: ClusterIP

