apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-grafana-datasources
  namespace: prod
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://monitoring-prometheus:9090
        isDefault: true
        editable: true

