apiVersion: v1
kind: Service
metadata:
  name: monitoring-grafana
  namespace: prod
  labels:
    app.kubernetes.io/name: monitoring-grafana
    app.kubernetes.io/part-of: test-microservice
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: testmicroservice-dev-grafana
spec:
  selector:
    app.kubernetes.io/name: monitoring-grafana
  ports:
    - name: http
      port: 80
      targetPort: http
  type: LoadBalancer

