apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-grafana
  namespace: dev
  labels:
    app.kubernetes.io/name: monitoring-grafana
    app.kubernetes.io/part-of: test-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: monitoring-grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: monitoring-grafana
        app.kubernetes.io/part-of: test-microservice
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:11.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: monitoring-grafana-admin
                  key: admin-user
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: monitoring-grafana-admin
                  key: admin-password
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "false"
          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboard-provider
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
      volumes:
        - name: datasources
          configMap:
            name: monitoring-grafana-datasources
        - name: dashboard-provider
          configMap:
            name: monitoring-grafana-dashboard-provider
        - name: dashboards
          configMap:
            name: monitoring-grafana-dashboard-webapp
