apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-quota
  namespace: prod
spec:
  hard:
    pods: "20"
    requests.cpu: "1000m"
    requests.memory: "1Gi"
    limits.cpu: "1500m"
    limits.memory: "2Gi"
    services: "10"
    persistentvolumeclaims: "4"

