apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  namespace: dev
data:
  ASPNETCORE_URLS: http://+:8080
  ASPNETCORE_ENVIRONMENT: Development
  EventBus__SubscriptionClientName: Ordering.webapp
  ConnectionStrings__eventbus: amqp://eshop:eshop@eventbus:5672/
  IdentityUrl: https://YOUR_IDENTITY_HOST
  CallBackUrl: https://YOUR_WEBAPP_HOST
  SessionCookieLifetimeMinutes: "60"
