apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: dev
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/part-of: test-microservice
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: testmicroservice-dev-webapp
spec:
  selector:
    app.kubernetes.io/name: webapp
  ports:
    - name: http
      port: 80
      targetPort: http
  type: LoadBalancer
