apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  namespace: dev
  labels:
    app.kubernetes.io/name: catalog-api
    app.kubernetes.io/part-of: test-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catalog-api
        app.kubernetes.io/part-of: test-microservice
    spec:
      containers:
        - name: catalog-api
          image: testmicroservicedevcqr4acr.azurecr.io/eshop/catalog.api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: catalog-api-config
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /alive
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
