apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  namespace: prod
data:
  ASPNETCORE_URLS: http://+:8080
  EventBus__SubscriptionClientName: Ordering.webapp
  SessionCookieLifetimeMinutes: "60"

