apiVersion: v1
kind: Service
metadata:
  name: basket-api
  namespace: prod
  labels:
    app.kubernetes.io/name: basket-api
    app.kubernetes.io/part-of: test-microservice
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: basket-api
  ports:
    - port: 80
      targetPort: http
      name: http

