apiVersion: v1
kind: Service
metadata:
  name: identitydb
  namespace: prod
  labels:
    app.kubernetes.io/name: identitydb
    app.kubernetes.io/part-of: test-microservice
spec:
  selector:
    app.kubernetes.io/name: identitydb
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  type: ClusterIP

