apiVersion: v1
kind: ConfigMap
metadata:
  name: ordering-api-config
  namespace: prod
data:
  ASPNETCORE_URLS: http://+:8080
  ASPNETCORE_ENVIRONMENT: Development
  ConnectionStrings__orderingdb: Host=orderingdb;Port=5432;Database=orderingdb;Username=postgres;Pooling=false;Include Error Detail=true
  ConnectionStrings__EventBus: amqp://eshop:eshop@eventbus:5672/
  Identity__Url: https://YOUR_IDENTITY_HOST

